services:
  - type: web
    name: chronis
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120"
    runtime: python
    pythonVersion: 3.11.9
